### ISSUE TITLE
Ableton 10

### ISSUE THREAD

**Issue by DystopianDisco** [aumhaa/m4m7#3]
Hello Aumhaa-

Hope you're well!How is support looking for Ableton 10? Will you be updating the Python scripts? As of now I don't believe they work for the new Beta. 

Cheers.

**Comment by aumhaa** [comment]
Absolutely!  I'm keeping the newer version of the repository in a private bitbucket at the moment, as there are incompatibilities between the Live9/Live10 versions of the scripts and I don't want to make a fresh start when Live10 comes out with a separate repository.  I will be removing some of the m4l content in order to properly update and monetize it for Max8 release (along with new material that hasn't been published yet).  The remainder will be published as a free Max Package in the near future, I'm working on some sort of installer for the Python stuff to make things easier for end-users to get going and deal with the all-to-frequent updates that are required to keep pace with Ableton's framework changes.  I'll also push a new directory with updated scripts for Livid controllers to Livid's version of the script repository once Live10 is released.

I spotted some small issues between my scripts and the most current build of Live10 the other day. I believe I fixed them all locally, but haven't pushed some of the newer edits to my private repository yet.  If you send me an email with a request for the stuff you need, I can send you a copy tomorrow after I've double-checked that everything is working correctly.  I'd be happy to have some feedback about them anyway ;)

**Comment by DystopianDisco** [comment]
Incredible Aumhaa! An installer for the python script would be brilliant. 

Running the most current build of 10. Looking specifically for the Livid DS1 Controller to be recognised by Live and used as as control surface. More than happy to provide feedback (email: dystopiandisco@protonmail.com)

Look forward to testing. 

Cheers :)

**Comment by DystopianDisco** [comment]
Hello Aumhaa-

You're probably aware - but incase not the DS1 Script works perfectly with the official Ableton 10 release. 

Thank you!

**Comment by aumhaa** [comment]
There was actually some problems with the session navigation and knob assignments, I’ve updated the repo with newer versions.

a

**Comment by Wallas86** [comment]
Hello, somehow the script has stopped working on some of the versions of
ableton 11, may I ask you to update it?

сб, 10 февр. 2018 г. в 23:42, amounra ***@***.***>:

**Comment by aumhaa** [comment]
Hey there, it’s been a longggg time….I haven’t this week, but I’m 99% positive nothing is broken.  Are you sure you’re using the right files?

https://github.com/aumhaa/m4m8￼
aumhaa/m4m8: Mod implementation for Live10/Max8
github.com
\

If you’re still having troubles can you please send me a log.txt from your setup so I can take a look and see what’s going on?

Cheers :) 

a
